return {
    -- {
    --     "yetone/avante.nvim",
    --     event = "VeryLazy",
    --     version = false,
    --     opts = {
    --         provider = "ollama",
    --         ollama = {
    --             endpoint = "http://192.168.68.54:11434",
    --             -- model = "qwen2.5-coder:3b",
    --             -- model = "qwen2.5-coder:1.5b",
    --             model = "gemma3:1b",
    --             disable_tools = true,
    --         },
    --     },
    --     -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
    --     build = "make",
    --     dependencies = {
    --         "nvim-treesitter/nvim-treesitter",
    --         "stevearc/dressing.nvim",
    --         "nvim-lua/plenary.nvim",
    --         "MunifTanjim/nui.nvim",
    --         "ibhagwan/fzf-lua",
    --         -- {
    --         --   -- support for image pasting
    --         --   "HakonHarnes/img-clip.nvim",
    --         --   event = "VeryLazy",
    --         --   opts = {
    --         --     -- recommended settings
    --         --     default = {
    --         --       embed_image_as_base64 = false,
    --         --       prompt_for_file_name = false,
    --         --       drag_and_drop = {
    --         --         insert_mode = true,
    --         --       },
    --         --       -- required for Windows users
    --         --       use_absolute_path = true,
    --         --     },
    --         --   },
    --         -- },
    --         {
    --             -- Make sure to set this up properly if you have lazy=true
    --             "MeanderingProgrammer/render-markdown.nvim",
    --             opts = {
    --                 file_types = { "markdown", "Avante" },
    --             },
    --             ft = { "markdown", "Avante" },
    --         },
    --     },
    -- },
}
