console_title_template = '{{ .HostName }}'
version = 3
final_space = true

[palette]
  brown = '#736659'
  darkbrown = '#24211E'
  darkgreen = '#444A2B'
  darkorange = '#B36B42'
  darktan = '#AC987D'
  green = '#77824A'
  grey = '#8A7A6B'
  lightblue = '#669977'
  orange = '#BB7844'
  red = '#B3664D'
  tan = '#D7C484'
  teal = '#5F865F'
  yellow = '#C9A654'

[secondary_prompt]
  template = '>> '
  foreground = 'p:yellow'
  background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = ' {{ .Path }} '
    foreground = 'p:orange'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      home_icon = '~/'
      style = 'full'

  [[blocks.segments]]
    template = '<p:green>[{{ .RepoName }}]</> <p:teal>({{ if .IsBare }}bare:{{ end }}{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}{{ if gt .StashCount 0 }}<p:teal>$</>{{ end }})</> {{ if .Merge }}<p:red>|MERGE|</> {{ else if .Rebase }}<p:red>|REBASE|</> {{ end }}'
    foreground = 'p:tan'
    background = 'transparent'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ''
      cache_duration = 'none'
      commit_icon = '@'
      fetch_bare_info = true
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = ' {{ .Shell }} <p:yellow>></>'
    foreground = 'p:darkgreen'
    background = 'transparent'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
