#!/bin/sh

###########################
### bspwm configuration ###
###########################

# Set workspaces to monitors
bspc monitor -d 1 2 3 4 5 6 7 8


# Hotkeys
pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc & 
#sxhkd -c ~/.config/bspwm/sxhkdrc &
setxkbmap -option caps:escape

# bspwm settings
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# other settings

# set key repeat delay (ms), repate rate (reps/s)
xset r rate 500 40 

# set screen scaling
xrandr --dpi 192

# load config from Xresources
xrdb ~/.Xresources

# add additional font locations
xset +fp /home/patrick/.fonts
xset +fp /home/patrick/.local/share/fonts
xset fp rehash

# set battery profile on startup 
system76-power profile battery


###### Autostart apps ######

"${HOME}/.cache/wal/colors.sh"

# Wallpaper
wal -R &

# Panel
~/.config/polybar/pibar-v3/launch.sh &

# Picom
picom -b &

# Notifications
dunst &

# Powertop
powertop --auto-tune

# Fix cursor
xsetroot -cursor_name left_ptr &

