#!/bin/sh

###########################
### bspwm configuration ###
###########################

# Set workspaces to monitors
# bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8
bspc monitor -d 1 2 3 4 5 6 7 8


# Hotkeys
pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &
setxkbmap -option caps:escape

# bspwm settings
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# other settings

# set key repeat delay (ms), repate rate (reps/s)
xset r rate 500 40

# set screen scaling
xrandr --dpi 192

# load config from Xresources
xrdb ~/.Xresources

# add additional font locations
xset +fp /home/patrick/.fonts
xset +fp /home/patrick/.local/share/fonts
xset fp rehash

# set battery profile on startup
# system76-power profile battery

# mouse settings
xinput --set-prop 11 321 0


###### Autostart apps ######

# "${HOME}/.cache/wal/colors.sh"
"$HOME/dotfiles/scripts/base16-darkearth.sh"

# Wallpaper
# wal -R &

# Panel
$SHELL $HOME/.config/polybar/pibar-v2/launch.sh &

# Picom
picom -b &

# Notifications
dunst &

# Powertop
# TODO: this needs to run with sudo, use polkit or systemd service
# powertop --auto-tune
feh --bg-fill "$HOME/Pictures/wallpapers/ayanami.jpg" &

# Fix cursor
xsetroot -cursor_name left_ptr &

