#!/bin/sh

###########################
### bspwm configuration ###
###########################

# Set workspaces to monitors
bspc monitor -d 1 2 3 4 5 6 7 8


# Hotkeys
pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc & 
#sxhkd -c ~/.config/bspwm/sxhkdrc &
setxkbmap -option caps:escape

# bspwm settings
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true



###### Autostart apps ######

"${HOME}/.cache/wal/colors.sh"

# Wallpaper
wal -R &

# Panel
~/.config/polybar/blocks/launch.sh &

# Picom
picom -b &

# Notifications

# Fix cursor
xsetroot -cursor_name left_ptr &
