[[template_config]]
target_template = "conference.typ"
populate_template = true
extra_templates = ["document.typ"]
template_names = ["main.typ"]

[template_config.template_vars]
author = "Patrick Dewey"
